name: bqplot_docs
channels:
 - conda-forge
dependencies:
 - python=3.5
 - traitlets
 - traittypes
 - widgetsnbextension
 - ipywidgets>=6.0.0b5
 - numpy
 - pandas
 - bqplot
 - pip:
    - jupyter_sphinx
